require 'rails_helper'

RSpec.describe Food do
  it 'exists' do
    attrs = { fdcId: 600_987,
              description: 'SWEET POTATOES',
              lowercaseDescription: 'sweet potatoes',
              dataType: 'Branded',
              gtinUpc: '070560951975',
              publishedDate: '2019-04-01',
              brandOwner: 'The Pictsweet Company',
              ingredients: 'SWEET POTATOES.',
              allHighlightFields: '<b>Ingredients</b>: <em>SWEET</em> <em>POTATOES</em>.',
              score: 905.80396,
              foodNutrients: [{ nutrientId: 1004,
                                nutrientName: 'Total lipid (fat)',
                                nutrientNumber: '204',
                                unitName: 'G',
                                derivationCode: 'LCCD',
                                derivationDescription: 'Calculated from a daily value percentage per serving size measure',
                                value: 0.0 },
                              { nutrientId: 1110,
                                nutrientName: 'Vitamin D (D2 + D3), International Units',
                                nutrientNumber: '324',
                                unitName: 'IU',
                                derivationCode: 'LCCD',
                                derivationDescription: 'Calculated from a daily value percentage per serving size measure',
                                value: 0.0 },
                              { nutrientId: 1253,
                                nutrientName: 'Cholesterol',
                                nutrientNumber: '601',
                                unitName: 'MG',
                                derivationCode: 'LCCD',
                                derivationDescription: 'Calculated from a daily value percentage per serving size measure',
                                value: 0.0 },
                              { nutrientId: 1258,
                                nutrientName: 'Fatty acids, total saturated',
                                nutrientNumber: '606',
                                unitName: 'G',
                                derivationCode: 'LCCD',
                                derivationDescription: 'Calculated from a daily value percentage per serving size measure',
                                value: 0.0 },
                              { nutrientId: 1003,
                                nutrientName: 'Protein',
                                nutrientNumber: '203',
                                unitName: 'G',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 1.69 },
                              { nutrientId: 1005,
                                nutrientName: 'Carbohydrate, by difference',
                                nutrientNumber: '205',
                                unitName: 'G',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 20.3 },
                              { nutrientId: 1008,
                                nutrientName: 'Energy',
                                nutrientNumber: '208',
                                unitName: 'KCAL',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 85.0 },
                              { nutrientId: 2000,
                                nutrientName: 'Sugars, total including NLEA',
                                nutrientNumber: '269',
                                unitName: 'G',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 4.24 },
                              { nutrientId: 1079,
                                nutrientName: 'Fiber, total dietary',
                                nutrientNumber: '291',
                                unitName: 'G',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 3.4 },
                              { nutrientId: 1087,
                                nutrientName: 'Calcium, Ca',
                                nutrientNumber: '301',
                                unitName: 'MG',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 30.0 },
                              { nutrientId: 1089,
                                nutrientName: 'Iron, Fe',
                                nutrientNumber: '303',
                                unitName: 'MG',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 0.85 },
                              { nutrientId: 1092,
                                nutrientName: 'Potassium, K',
                                nutrientNumber: '306',
                                unitName: 'MG',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 337 },
                              { nutrientId: 1093,
                                nutrientName: 'Sodium, Na',
                                nutrientNumber: '307',
                                unitName: 'MG',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 55.0 },
                              { nutrientId: 1257,
                                nutrientName: 'Fatty acids, total trans',
                                nutrientNumber: '605',
                                unitName: 'G',
                                derivationCode: 'LCCS',
                                derivationDescription: 'Calculated from value per serving size measure',
                                value: 0.0 }] }

    food = Food.new(attrs)

    expect(food).to be_a Food
    expect(food.code).to eq('070560951975')
    expect(food.description).to eq('SWEET POTATOES')
    expect(food.brand).to eq('The Pictsweet Company')
    expect(food.ingredients).to eq('SWEET POTATOES.')
  end
end
